 
version: '2'
services:
  tasks:
    build:
      context: ./TaskService
  api:
    build:
      context: ./ApiGateway
    environment:
      - "TASK_API=http://tasks:5000"
    depends_on:
      - tasks
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./Frontend
    ports:
      - "8080:80"